version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: [db_data:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  backend:
    build: ./apps/backend
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    ports: ["5000:5000"]
    depends_on: [db]

  frontend:
    build: ./apps/frontend
    ports: ["8080:80"]
    depends_on: [backend]

volumes:
  db_data:
